apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: todo-list-api
spec:
  selector:
    matchLabels:
      app: todo-list-api
  replicas: 1
  template:
    metadata:
      labels:
        app: todo-list-api
    spec:
      containers:
      - name: todo-list-api
        image: todo-list-api:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: api-service
          containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: todo-list-api
  ports:
  - nodePort: 31317
    port: 8000
    protocol: TCP
    targetPort: 8000